// Auto-generated safelist for @kaiserinc/react Tailwind classes.
// Tailwind scans this file so it generates all classes used by @kaiserinc/react.
// DO NOT DELETE — removing this breaks @kaiserinc/react component styling.
// Regenerate: node scripts/gen-kaiserinc-safelist.mjs (if script exists)

// biome-ignore-all
/* eslint-disable */
export const KAISERINC_SAFELIST = [
  "!bg-[var(--bg-elevated)] !text-[var(--fg-2)] text-xs rounded-[var(--radius-sm)] px-2 py-1",
  "!bg-[var(--brand)] !text-white text-xs rounded-[var(--radius-sm)] px-2 py-1",
  "!border-l-4 !border-l-[var(--brand)]",
  "!border-l-4 !border-l-[var(--danger-500)]",
  "!border-l-4 !border-l-[var(--success-500)]",
  "!border-l-4 !border-l-[var(--warning-500)]",
  "!text-[var(--fg-3)] text-sm font-normal",
  "!text-[var(--fg-4)] hover:!text-[var(--fg-1)]",
  ", style: { transition:",
  "-translate-x-0",
  "absolute inset-0 -translate-x-full animate-[shimmer_1.5s_infinite] bg-gradient-to-r from-transparent via-white/5 to-transparent",
  "absolute left-3 flex items-center text-[var(--fg-4)] pointer-events-none",
  "absolute right-3 flex items-center text-[var(--fg-4)]",
  "absolute top-full mt-1 z-50 min-w-[180px]",
  "absolute top-full mt-1 z-50 w-full min-w-[180px]",
  "absolute w-0 h-0 border-4",
  "absolute z-50 min-w-[200px]",
  "absolute z-50 whitespace-nowrap",
  "active:bg-[var(--brand-active)]",
  "after:absolute after:bottom-[-1px] after:left-0 after:right-0",
  "after:h-0.5 after:bg-[var(--brand)]",
  "animate-pulse bg-[var(--bg-elevated)] relative overflow-hidden",
  "aria-hidden",
  "bg-[rgba(0,179,126,0.08)] border-l-4 border-[var(--success-500)]",
  "bg-[rgba(0,179,126,0.12)] text-[var(--success-500)] border border-[rgba(0,179,126,0.3)]",
  "bg-[rgba(247,90,104,0.08)] border-l-4 border-[var(--danger-500)]",
  "bg-[rgba(247,90,104,0.12)] text-[var(--danger-500)] border border-[rgba(247,90,104,0.3)]",
  "bg-[rgba(251,169,76,0.08)] border-l-4 border-[var(--warning-500)]",
  "bg-[rgba(251,169,76,0.12)] text-[var(--warning-500)] border border-[rgba(251,169,76,0.3)]",
  "bg-[var(--bg-base)] border-b border-[var(--border-subtle)]",
  "bg-[var(--bg-elevated)] border border-[var(--border-default)]",
  "bg-[var(--bg-elevated)] border-b border-[var(--border-default)]",
  "bg-[var(--bg-elevated)] text-[var(--fg-2)]",
  "bg-[var(--bg-elevated)] text-[var(--fg-2)] border border-[var(--border-default)]",
  "bg-[var(--bg-elevated)]/40",
  "bg-[var(--bg-surface)] border border-[var(--border-default)]",
  "bg-[var(--border-default)]",
  "bg-[var(--brand)]",
  "bg-[var(--brand)] border-[var(--brand)]",
  "bg-[var(--brand)] text-[var(--fg-1)]",
  "bg-[var(--brand)] text-white font-semibold",
  "bg-[var(--brand)] text-white text-sm font-medium",
  "bg-[var(--brand-subtle)] border-l-4 border-[var(--brand)]",
  "bg-[var(--brand-subtle)] text-[var(--brand)]",
  "bg-[var(--brand-subtle)] text-[var(--brand)] border border-[var(--brand-muted)]",
  "bg-[var(--danger-500)]",
  "bg-[var(--fg-3)]",
  "bg-[var(--gray-800,#1f2937)] text-white text-xs",
  "bg-[var(--success-500)]",
  "bg-[var(--warning-500)]",
  "bg-transparent border-[var(--border-default)]",
  "bg-transparent text-[var(--brand)]",
  "bg-transparent text-[var(--danger-500)]",
  "bg-transparent text-[var(--fg-3)]",
  "bg-white",
  "border border-[var(--border-default)]",
  "border border-[var(--border-default)] text-[var(--fg-1)] text-sm",
  "border border-[var(--border-subtle)]",
  "border border-[var(--border-subtle)] p-5",
  "border border-[var(--brand)]",
  "border border-[var(--danger-500)]",
  "border-0 p-0 m-0",
  "border-[var(--danger-500)] focus:shadow-[0_0_0_3px_rgba(247,90,104,0.4)]",
  "border-b border-[var(--border-subtle)]",
  "bottom",
  "bottom-0 left-0 w-full max-h-[50vh]",
  "bottom-full left-1/2 -translate-x-1/2 border-l-transparent border-r-transparent border-t-transparent border-b-[var(--gray-800,#1f2937)]",
  "bottom-full left-1/2 -translate-x-1/2 mb-2",
  "bottom-full mb-2",
  "bottom-right",
  "cursor-pointer",
  "disabled:opacity-50 disabled:cursor-not-allowed",
  "divide-y divide-[var(--border-subtle)]",
  "fixed inset-0 z-50 bg-black/60 backdrop-blur-sm",
  "fixed inset-0 z-50 flex items-center justify-center p-4",
  "fixed z-50 flex flex-col bg-[var(--bg-surface)] border border-[var(--border-default)] shadow-[var(--shadow-md)]",
  "flex border-b border-[var(--border-subtle)]",
  "flex flex-col",
  "flex flex-col gap-1.5",
  "flex flex-col gap-2",
  "flex flex-col gap-3",
  "flex flex-col h-full bg-[var(--bg-surface)]",
  "flex flex-col items-center justify-center text-center py-12 px-6",
  "flex flex-col max-h-[90vh]",
  "flex gap-3 rounded-[var(--radius-md)] px-4 py-3",
  "flex items-center gap-1",
  "flex items-center gap-1 text-sm",
  "flex items-center gap-1.5",
  "flex items-center gap-1.5 text-xs text-[var(--fg-4)]",
  "flex items-center gap-2 flex-shrink-0",
  "flex items-center gap-2 w-full px-3 py-2 text-sm text-left",
  "flex items-center gap-3 justify-end px-6 py-4 border-t border-[var(--border-subtle)]",
  "flex items-center gap-3 mb-4",
  "flex items-center gap-3 w-full",
  "flex items-center gap-3 w-full rounded-[var(--radius-md)]",
  "flex items-center gap-4 min-w-0",
  "flex items-center h-16 flex-shrink-0 px-4",
  "flex items-center justify-between",
  "flex items-center justify-between gap-4 px-6",
  "flex items-center justify-between px-6 py-4 border-b border-[var(--border-subtle)]",
  "flex items-center justify-center flex-shrink-0 cursor-pointer",
  "flex items-center justify-center h-8 w-8 rounded-[var(--radius-lg)] bg-[var(--brand-subtle)] text-[var(--brand)]",
  "flex items-center justify-end gap-3 px-6 pb-6 pt-4 border-t border-[var(--border-subtle)]",
  "flex items-center px-4 py-2.5 text-sm cursor-pointer",
  "flex items-end gap-2",
  "flex items-start gap-3 cursor-pointer",
  "flex items-start justify-between gap-4 px-6 pt-6 pb-4 border-b border-[var(--border-subtle)]",
  "flex w-full items-center justify-between py-3 px-1 text-sm font-medium text-left",
  "flex-1 h-px bg-[var(--border-subtle)]",
  "flex-1 min-w-0",
  "flex-1 overflow-y-auto px-6 py-4",
  "flex-1 overflow-y-auto px-6 py-4 text-sm text-[var(--fg-2)]",
  "flex-1 overflow-y-auto py-4 space-y-6 px-2",
  "flex-1 text-left truncate",
  "flex-shrink-0",
  "flex-shrink-0 -mt-0.5 -mr-1 p-1 rounded",
  "flex-shrink-0 p-4 border-t border-[var(--border-subtle)]",
  "flex-shrink-0 select-none",
  "flex-shrink-0 text-[var(--fg-4)]",
  "flex-shrink-0 text-[var(--fg-4)] transition-transform duration-[var(--duration-fast)]",
  "flex-shrink-0 text-xs bg-[var(--brand-subtle)] text-[var(--brand)] px-1.5 py-0.5 rounded-[var(--radius-pill)]",
  "focus-visible:outline-none",
  "focus-visible:outline-none focus-visible:shadow-[var(--shadow-focus)]",
  "focus-visible:outline-none focus-visible:shadow-[var(--shadow-focus)] rounded-[var(--radius-sm)]",
  "focus-visible:shadow-[var(--shadow-focus)]",
  "focus:outline-none",
  "focus:outline-none focus:bg-[var(--bg-elevated)]",
  "focus:outline-none focus:border-[var(--brand)]",
  "focus:outline-none focus:border-[var(--brand)] focus:shadow-[var(--shadow-focus)]",
  "focus:shadow-[var(--shadow-focus)]",
  "font-medium text-[var(--brand)]",
  "font-medium text-[var(--fg-2)] leading-none",
  "grid",
  "grid-template-rows 300ms cubic-bezier(0.4, 0, 0.2, 1)",
  "h-1.5 w-1.5",
  "h-10",
  "h-10 justify-center px-2",
  "h-10 px-4 text-sm gap-2",
  "h-10 w-10",
  "h-10 w-10 text-sm",
  "h-11 w-full min-w-[180px] flex items-center justify-between",
  "h-12 px-6 text-base gap-2.5",
  "h-12 w-12 text-base",
  "h-14",
  "h-14 w-14",
  "h-16 w-16 text-lg",
  "h-2 w-2",
  "h-2/3 w-2/3",
  "h-3 w-3",
  "h-3.5 w-3.5",
  "h-3/5 w-3/5 text-[var(--fg-4)]",
  "h-4 w-4",
  "h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent",
  "h-5 w-5",
  "h-6 w-6",
  "h-6 w-6 text-xs",
  "h-8 px-3 text-sm gap-1.5",
  "h-8 w-8",
  "h-8 w-8 text-xs",
  "h-9 px-3",
  "h-full rounded-full transition-[width] duration-300 ease-out",
  "h-full w-full object-cover",
  "h-full w-px bg-[var(--border-subtle)] flex-shrink-0",
  "hidden",
  "hover:bg-[var(--bg-elevated)]",
  "hover:bg-[var(--bg-elevated)] hover:text-[var(--fg-1)]",
  "hover:bg-[var(--bg-elevated)]/60",
  "hover:bg-[var(--brand-hover)]",
  "hover:bg-[var(--brand-hover)] active:bg-[var(--brand-active)]",
  "hover:bg-[var(--brand-subtle)]",
  "hover:bg-[var(--danger-500)] hover:text-white",
  "hover:border-[var(--border-default)] hover:-translate-y-px hover:shadow-[var(--shadow-md)]",
  "hover:border-[var(--border-strong)] hover:text-[var(--fg-1)]",
  "hover:text-[var(--fg-2)] transition-colors",
  "inline-block",
  "inline-flex items-center gap-1",
  "inline-flex items-center gap-2",
  "inline-flex items-center justify-center gap-2 h-10 px-4",
  "inline-flex items-center justify-center h-8 min-w-[2rem] px-2",
  "inline-flex items-center justify-center rounded-[var(--radius-md)] font-medium",
  "inline-flex items-center rounded-[var(--radius-pill)] font-medium",
  "left-0",
  "left-0 top-0 h-full w-80 max-w-full",
  "left-1/2 -translate-x-1/2",
  "left-full ml-2 top-0",
  "left-full top-1/2 -translate-y-1/2 border-t-transparent border-b-transparent border-r-transparent border-l-[var(--gray-800,#1f2937)]",
  "left-full top-1/2 -translate-y-1/2 ml-2",
  "max-w-2xl",
  "max-w-lg",
  "max-w-sm",
  "min-w-0",
  "ml-1 text-[var(--danger-500)]",
  "ml-auto flex-shrink-0 text-[var(--brand)]",
  "mt-0.5 flex-shrink-0",
  "mt-0.5 h-4 w-4 accent-[var(--brand)] cursor-pointer",
  "my-1 h-px bg-[var(--border-subtle)]",
  "object-contain select-none",
  "opacity-50 cursor-not-allowed",
  "overflow-hidden text-sm text-[var(--fg-3)]",
  "pb-3 px-1",
  "placeholder:text-[var(--fg-5)]",
  "pointer-events-none",
  "px-1.5 py-0.5 text-xs",
  "px-2 py-1 rounded-[var(--radius-sm)] shadow-lg",
  "px-2 py-1 text-xs",
  "px-2 text-sm text-[var(--fg-4)]",
  "px-3 py-1.5 text-xs font-semibold text-[var(--fg-4)] uppercase tracking-wide",
  "px-3 py-2",
  "px-4 py-3 text-[var(--fg-2)]",
  "px-4 py-3 text-left text-xs font-semibold text-[var(--fg-4)] uppercase tracking-wider",
  "py-1",
  "py-1.5 max-h-60 overflow-y-auto",
  "py-2 text-xs text-[var(--fg-4)] text-left px-4",
  "py-4",
  "relative",
  "relative flex items-center",
  "relative flex items-center justify-center",
  "relative inline-flex",
  "relative inline-flex flex-shrink-0 items-center rounded-full",
  "relative inline-flex items-center justify-center rounded-full overflow-hidden",
  "relative px-4 py-2 text-sm font-medium whitespace-nowrap",
  "relative w-full bg-[var(--bg-surface)] border border-[var(--border-default)]",
  "right",
  "right-0",
  "right-0 top-0 h-full w-80 max-w-full",
  "right-full mr-2 top-0",
  "right-full top-1/2 -translate-y-1/2 border-t-transparent border-b-transparent border-l-transparent border-r-[var(--gray-800,#1f2937)]",
  "right-full top-1/2 -translate-y-1/2 mr-2",
  "rotate-180",
  "rounded-[var(--radius-lg)]",
  "rounded-[var(--radius-lg)] shadow-[var(--shadow-md)]",
  "rounded-[var(--radius-md)]",
  "rounded-[var(--radius-md)] bg-[var(--bg-elevated)]",
  "rounded-[var(--radius-md)] transition-colors duration-[var(--duration-base)]",
  "rounded-[var(--radius-sm)]",
  "rounded-[var(--radius-sm)] border transition-colors duration-[var(--duration-base)]",
  "rounded-[var(--radius-xl)] bg-[var(--bg-surface)]",
  "rounded-[var(--radius-xl)] shadow-[var(--shadow-md)]",
  "rounded-full",
  "rounded-full animate-bounce",
  "rounded-full bg-white shadow transition-transform duration-[var(--duration-base)] ease-[var(--ease-out)]",
  "select-none",
  "select:not([disabled])",
  "space-y-0.5",
  "space-y-4",
  "sr-only",
  "sticky top-0 z-40 h-16",
  "text-3xl font-bold text-[var(--fg-1)] leading-none",
  "text-[var(--brand)]",
  "text-[var(--danger-500)]",
  "text-[var(--fg-1)]",
  "text-[var(--fg-1)] transition-colors duration-[var(--duration-fast)] hover:text-[var(--brand)]",
  "text-[var(--fg-2)] font-medium",
  "text-[var(--fg-3)] hover:bg-[var(--bg-elevated)] hover:text-[var(--fg-1)]",
  "text-[var(--fg-4)]",
  "text-[var(--fg-4)] hover:text-[var(--fg-2)]",
  "text-[var(--fg-5)] flex-shrink-0",
  "text-[var(--fg-5)] mb-4",
  "text-[var(--success-500)]",
  "text-[var(--warning-500)]",
  "text-base font-bold text-[var(--fg-1)] leading-tight",
  "text-base font-bold text-[var(--fg-1)] leading-tight truncate",
  "text-base font-semibold text-[var(--fg-1)]",
  "text-base font-semibold text-[var(--fg-1)] mb-1",
  "text-lg font-semibold text-[var(--fg-1)] leading-tight",
  "text-sm font-medium leading-none mb-0.5",
  "text-sm font-medium text-[var(--fg-1)]",
  "text-sm font-medium text-[var(--fg-2)]",
  "text-sm font-medium text-[var(--fg-2)] leading-none",
  "text-sm font-medium text-[var(--fg-2)] mb-2",
  "text-sm font-medium text-[var(--fg-3)]",
  "text-sm font-medium transition-all duration-[var(--duration-fast)]",
  "text-sm pl-4 pr-3 text-left",
  "text-sm rounded-[var(--radius-md)]",
  "text-sm text-[var(--fg-2)]",
  "text-sm text-[var(--fg-2)] leading-5",
  "text-sm text-[var(--fg-2)] leading-none select-none",
  "text-sm text-[var(--fg-2)] leading-none select-none cursor-pointer",
  "text-sm text-[var(--fg-3)]",
  "text-xs text-[var(--fg-4)]",
  "text-xs text-[var(--fg-4)] tabular-nums",
  "text-xs text-[var(--fg-4)] whitespace-nowrap select-none",
  "top-0 left-0 w-full max-h-[50vh]",
  "top-full left-1/2 -translate-x-1/2 border-l-transparent border-r-transparent border-b-transparent border-t-[var(--gray-800,#1f2937)]",
  "top-full left-1/2 -translate-x-1/2 mt-2",
  "top-full mt-2",
  "transition-all duration-[var(--duration-base)] ease-[var(--ease-out)]",
  "transition-colors duration-[var(--duration-base)]",
  "transition-colors duration-[var(--duration-base)] ease-[var(--ease-out)]",
  "transition-colors duration-[var(--duration-fast)]",
  "translate-x-0",
  "translate-x-0.5",
  "translate-x-1",
  "translate-x-4",
  "translate-x-6",
  "translate-y-0",
  "truncate",
  "w-11 h-6",
  "w-16",
  "w-64",
  "w-8 h-4",
  "w-full h-10 rounded-[var(--radius-md)] bg-[var(--bg-elevated)]",
  "w-full h-px bg-[var(--border-subtle)]",
  "w-full min-h-[80px] rounded-[var(--radius-md)] bg-[var(--bg-elevated)]",
  "w-full overflow-x-auto rounded-[var(--radius-lg)] border border-[var(--border-subtle)]",
  "w-full rounded-full bg-[var(--bg-elevated)] overflow-hidden",
  "w-full text-sm border-collapse"
] as const;
